### ISSUE TITLE
where is the MegaEncoderCounter.h file?

### ISSUE THREAD

**Issue by 78226415** [LordBismaya/ros_arduino_bridge#1]
Hi every one,
     I have a look at the file MegaRobogaiaPololu.ino in ros_arduino_firmware, it includes a file: MegaEncoderCounter.h, but i have not find it, could some one help me ? 

thanks

**Comment by LordBismaya** [comment]
Hi, I didnt expect traffic on this page. Its a personal project I have been working on. But to answer your question, Please read the ReadMe. There are links describing where to download the libraries. You have to download the libraries and add to them to your arduino project before you can compile the whole thing. 

Essentially, the libraries are a part of the Pololu encoders specifically and might not adhere to your needs. But u can made necessary changes wherever you need it. 

Goodluck!

**Comment by 78226415** [comment]
thanks
